services:
  db:
    image: postgres:16
    container_name: syncal_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: syncal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
 
volumes:
  pgdata:
    name: syncal_pgdata

#Para levantar docker correr (parados en SynCal): docker compose --env-file .env -f config/docker-compose.yml up -d
#Para bajarlo (parados en SynCal): docker compose -f config/docker-compose.yml down